[[plugins]]
repo = 'neomake/neomake'
on_ft = ["python", "python3", "djangohtml", "jinja"]
if = "has('nvim')"
hook_source = '''
    autocmd! BufEnter,BufWritePost * Neomake
    let g:neomake_python_enabled_makers = ['python', 'flake8', 'mypy']
'''

[[plugins]]
repo = 'vim-syntastic/syntastic'
on_ft = ["python", "python3", "djangohtml", "jinja"]
if = "!has('nvim')"
hook_source = '''
    let g:syntastic_always_populate_loc_list = 1
    let g:syntastic_check_on_open = 1
    let g:syntastic_check_on_wq = 0
    " for Python
    let g:syntastic_python_checkers = ['python', 'flake8', 'mypy']
'''

[[plugins]]
repo = "davidhalter/jedi-vim"
# depends = ["vim-pyenv"]
on_ft = ["python", "python3", "djangohtml", "jinja"]
# on_source = "lambdalisue/vim-pyenv"
hook_post_update = '''
    if dein#util#_is_windows()
        let cmd = 'pip install jedi'
    elseif dein#util#_is_unix()
        let cmd = 'pip install jedi'
    else
        let cmd = 'pip install jedi'
    endif
'''
hook_source  = '''
    " PATHの自動更新関数
    autocmd FileType python setlocal completeopt-=preview
    autocmd FileType python setlocal omnifunc=jedi#completions
    let g:jedi#completions_enabled = 0
    " jediにvimの設定を任せると'completeopt+=preview'するので
    " 自動設定機能をOFFにし手動で設定を行う
    let g:jedi#auto_vim_configuration=0
    " 補完の最初の項目が選択された状態だと使いにくいためオフにする
    let g:jedi#popup_select_first=0
    " quickrunと被るため大文字に変更
    let g:jedi#rename_command='<Leader>R'
    " gundoと被るため大文字に変更 (2013-06-24 10:00 追記）
    let g:jedi#goto_command='<Leader>G'
    let g:jedi#goto_assignments_command = "<C-g>"   " 変数の宣言場所へジャンプ（Ctrl + g)
    let g:jedi#goto_definitions_command = "<C-d>"   " クラス、関数定義にジャンプ（Gtrl + d）
    let g:jedi#documentation_command = "<C-k>"      " Pydocを表示（Ctrl + k）
    let g:jedi#completions_command = '<C-Space>'

    if !exists('g:neocomplete#force_omni_input_patterns')
            let g:neocomplete#force_omni_input_patterns = {}
    endif
    let g:neocomplete#force_omni_input_patterns.python = '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*'
    " let g:neocomplete#force_omni_input_patterns.python = '\h\w*\|[^. \t]\.\w*'
    "pyenv の補完を有効にする
'''
hook_post_source = '''
    python print sys.path
'''

[[plugins]]
repo = 'google/yapf'
on_ft = ["python", "python3", "djangohtml", "jinja"]
rtp = "plugins/vim"

# [[plugins]]
# repo = 'andviro/flake8-vim'
# on_ft = ["python", "python3", "djangohtml", "jinja"]
